# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\Participant: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Participant
                property: pseudo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
            entry_point: form_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }